web-app/asqatasun-web-app/src/main/java/org/asqatasun/webapp/dto/AuditStatistics.java
/*
 * Asqatasun - Automated webpage assessment
 * Copyright (C) 2008-2020  Asqatasun.org
 *
 * This file is part of Asqatasun.
 *
 * Asqatasun is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contact us by mail: asqatasun AT asqatasun DOT org
 */
package org.asqatasun.webapp.dto;

import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;
import org.asqatasun.entity.reference.Theme;
import org.asqatasun.entity.contract.ScopeEnum;
import org.asqatasun.webapp.util.TgolEscapeUrl;

/**
 * This class handles displayable audit statistics data
 * @author jkowalczyk
 */
public class AuditStatistics {

    /**
     * The url of the checked page
     */
    private String url = null;
    /**
     *
     * @return
     */
    public String getUrl() {
        return url;
    }
    /**
     *
     * @param url
     */
    public void setUrl(String url) {
        this.url = TgolEscapeUrl.escapeUrl(url);
    }
    /**
     * The url of the checked page
     */
    private String snapshotUrl = null;
    /**
     *
     * @return
     */
    public String getSnapshotUrl() {
        return snapshotUrl;
    }
    /**
     *
     * @param snaphostUrl
     */
    public void setSnapshotUrl(String snaphostUrl) {
        this.snapshotUrl = TgolEscapeUrl.escapeUrl(snaphostUrl);
    }

    /**
     * The final mark of the audit
     */
    private String rawMark;
    /**
     *
     * @return
     */
    public String getRawMark() {
        return rawMark;
    }

    /**
     *
     * @param rawMark
     */
    public void setRawMark(String rawMark) {
        this.rawMark = rawMark;
    }

    /**
     * The mark of the audit
     */
    private String weightedMark;
    /**
     *
     * @return
     */
    public String getWeightedMark() {
        return weightedMark;
    }

    /**
     *
     * @param weightedMark
     */
    public void setWeightedMark(String weightedMark) {
        this.weightedMark = weightedMark;
    }

    /**
     * The date of the audit
     */
    private Date date = null;
    /**
     *
     * @return
     */
    public Date getDate() {
        if (date != null) {
            return new Date(date.getTime());
        } else {
            return null;
        }
    }

    /**
     *
     * @param date
     */
    public void setDate(Date date) {
        if (date != null) {
            this.date = new Date(date.getTime());
        }
    }

    private ResultCounter resultCounter = new ResultCounter();
    /**
     *
     * @return
     */
    public ResultCounter getResultCounter() {
        return resultCounter;
    }

    /**
     *
     * @param resultCounter
     */
    public void setResultCounter(ResultCounter resultCounter) {
        this.resultCounter = resultCounter;
    }

    /**
     * The map that handles the results count by theme
     */
    private Map<Theme, ResultCounter> counterByThemeMap;
    /**
     *
     * @return
     */
    public Map<Theme, ResultCounter> getCounterByThemeMap() {
        return counterByThemeMap;
    }

    /**
     *
     * @param counterByThemeMap
     */
    public void setCounterByThemeMap(Map<Theme, ResultCounter> counterByThemeMap) {
        this.counterByThemeMap = counterByThemeMap;
    }

    /**
     *
     * @return
     */
    public int getTestCount(){
        return resultCounter.getNmiCount() +
               resultCounter.getNaCount() +
               resultCounter.getPassedCount() +
               resultCounter.getFailedCount();
    }

    private Integer pageCounter;
    /**
     *
     * @return
     */
    public Integer getPageCounter() {
        return pageCounter;
    }

    /**
     *
     * @param pageCounter
     */
    public void setPageCounter(Integer pageCounter) {
        this.pageCounter = pageCounter;
    }

    private Map<String, String> parametersMap = new LinkedHashMap();
    /**
     *
     * @return
     */
    public Map<String, String> getParametersMap() {
        return parametersMap;
    }

    /**
     * 
     * @param parametersMap
     */
    public void setParametersMap(Map<String, String> parametersMap) {
        this.parametersMap = parametersMap;
    }

    private ScopeEnum auditScope;
    /**
     * 
     * @return
     */
    public ScopeEnum getAuditScope() {
        return auditScope;
    }

    /**
     * 
     * @param auditScope
     */
    public void setAuditScope(ScopeEnum auditScope) {
        this.auditScope = auditScope;
    }

    private Integer auditedPageCounter;
    public Integer getAuditedPageCounter() {
        return auditedPageCounter;
    }
    public void setAuditedPageCounter(Integer auditedPageCounter) {
        this.auditedPageCounter = auditedPageCounter;
    }

}

web-app/asqatasun-web-app/src/main/java/org/asqatasun/webapp/controller/LoginController.java
/*
 * Asqatasun - Automated webpage assessment
 * Copyright (C) 2008-2020  Asqatasun.org
 *
 * This file is part of Asqatasun.
 *
 * Asqatasun is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contact us by mail: asqatasun AT asqatasun DOT org
 */
package org.asqatasun.webapp.controller;

import org.asqatasun.webapp.util.TgolKeyStore;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

import static org.asqatasun.webapp.util.TgolKeyStore.*;

/** 
 *
 * @author jkowalczyk
 */
@Controller
public class LoginController extends AbstractUserAndContractsController{


    @GetMapping(value = {LOGIN_URL, "/"})
    public String displayLoginPage () {
        return (isAuthenticated())? HOME_VIEW_REDIRECT_NAME: LOGIN_VIEW_NAME;
    }

    @GetMapping(value = ACCESS_DENIED_URL)
    public String displayAccessDeniedPage() {
        return ACCESS_DENIED_VIEW_NAME;
    }


}

web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/template/add-edit-contract.jsp
<%@ taglib uri="http://htmlcompressor.googlecode.com/taglib/compressor" prefix="compress" %>
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib uri="http://tagutils" prefix="tg" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<div class="span16">
    <div id="mandatory-elements-message" 
         class="alert-message block-message warning">
        <spring:message code="sign-up.mandatoryElementsMessage"/>
    </div>
</div>
<div class="span16">
    <div id="account-settings-form">
        <form:form method="post" 
                   modelAttribute="createContractCommand" 
                   acceptCharset="UTF-8" 
                   enctype="application/x-www-form-urlencoded">
            <spring:hasBindErrors name="createContractCommand">
            <div id="sign-up-form-general-error">
                <form:errors path="generalErrorMsg" 
                             cssClass="alert-message block-message error" 
                             element="div"/>
            </div>
            </spring:hasBindErrors>
            <c:if test="${not empty userList}">
                <c:set var="userListError">
                    <form:errors path="userList"/>
                </c:set>
                <c:if test="${not empty userListError}">
                    <c:set var="userListErrorClass" value="error"/>
                </c:if>
            <div class="clearfix ${userListErrorClass}">
                <label id="user-list-label" for="userList">
                    <fmt:message key="add-contract.users"/>
                </label>
                <div class="input" >
                <c:choose>
                    <c:when test="${fn:length(userList) < 10}">
                        <c:set var="selectSize" value="${fn:length(userList)}"/>
                    </c:when>
                    <c:otherwise>
                        <c:set var="selectSize" value="10"/>
                    </c:otherwise>
                </c:choose>
                    <form:select multiple="true" 
                             path="userList" 
                             size="${selectSize}" 
                             class="xlarge" 
                             items="${userList}" 
                             itemValue="id" 
                             itemLabel="email1"/>
                    <form:errors path="userList" cssClass="alert-message error" />
                </div>
            </div>
            </c:if>
            <c:set var="labelError"><form:errors path="label"/></c:set>
            <c:if test="${not empty labelError}">
                <c:set var="labelErrorClass" value="error"/>
            </c:if>
            <div class="clearfix ${labelErrorClass}">
                <label id="label-label" for="label">
                    <fmt:message key="edit-contract.contractLabel"/>
                </label>
                <div class="input" >
                    <form:input path="label" 
                                cssErrorClass="xlarge error" 
                                cssClass="xlarge"/>
                    <form:errors path="label" 
                                 cssClass="alert-message error" />
                </div>
            </div>
            <c:set var="beginDateError">
                <form:errors path="beginDate"/>
            </c:set>
            <c:if test="${not empty beginDateError}">
                <c:set var="beginDateErrorClass" value="error"/>
            </c:if>
            <div class="clearfix ${beginDateErrorClass}">
                <label id="begin-date-label" 
                       for="beginDate">
                    <fmt:message key="edit-contract.contractBeginDate"/>
                </label>
                <div class="input" >
                    <form:input path="beginDate" 
                                cssErrorClass="xlarge error" 
                                cssClass="xlarge"/>
                    <form:errors path="beginDate" 
                                 cssClass="alert-message error" />
                    <span class="help-block">
                        <fmt:message key="edit-contract.contractBeginDateRule"/>
                    </span>
                </div>
            </div><!-- class="clearfix"-->
            <c:set var="endDateError">
                <form:errors path="endDate"/>
            </c:set>
            <c:if test="${not empty endDateError}">
                <c:set var="endDateErrorClass" value="error"/>
            </c:if>
            <div class="clearfix ${endDateErrorClass}">
                <label id="end-date-label" 
                       for="endDate">
                    <fmt:message key="edit-contract.contractEndDate"/>
                </label>
                <div class="input" >
                    <form:input path="endDate" 
                                cssErrorClass="xlarge error" 
                                cssClass="xlarge"/>
                    <form:errors path="endDate" 
                                 cssClass="alert-message error" />
                    <span class="help-block">
                        <fmt:message key="edit-contract.contractEndDateRule"/>
                    </span>
                </div>
            </div><!-- class="clearfix"-->
            <c:set var="contractUrlError">
                <form:errors path="contractUrl"/>
            </c:set>
            <c:if test="${not empty contractUrlError}">
                <c:set var="contractUrlErrorClass" value="error"/>
            </c:if>
            <div class="clearfix ${contractUrlErrorClass}">
                <label id="url-label" 
                       for="contractUrl">
                    <fmt:message key="edit-contract.contractUrl"/>
                </label>
                <div class="input" >
                    <form:input path="contractUrl"
                                cssErrorClass="xlarge error"
                                cssClass="xlarge"/>
                    <form:errors path="contractUrl"
                                 cssClass="alert-message error" />
                </div>
            </div><!-- class="clearfix"-->
            <fieldset>
                <legend>
                    <fmt:message key="edit-contract.referentials"/>
                </legend>
                <div class="clearfix edit-contract-checkbox-block">
                <c:forEach items="${createContractCommand.referentialMap}" 
                           var="ref" 
                           varStatus="pRefInput">
                    <span class="edit-contract-ref">
                    <c:set var="refKey">
                        ${ref.key}
                    </c:set>
                        <label id="${refKey}" 
                               for="referentialMap${refKey}1" 
                               class="edit-contract-label">
                            <fmt:message key="${refKey}"/>
                        </label>
                        <form:checkbox path="referentialMap[${refKey}]" 
                                       cssErrorClass="error" 
                                       value="${ref.value}" />
                        <form:errors path="referentialMap[${refKey}]" 
                                     cssClass="alert-message error" />
                    </span>
                </c:forEach>
                </div>
            </fieldset>
            <fieldset>
                <legend>
                    <fmt:message key="edit-contract.functionalities"/>
                </legend>
                <div class="clearfix edit-contract-checkbox-block">
                <c:forEach items="${createContractCommand.functionalityMap}" 
                           var="funct" 
                           varStatus="pFunctInput">
                    <c:set var="functKey">
                        ${funct.key}
                    </c:set>
                    <span class="edit-contract-funct">
                        <label id="${functKey}"
                               for="functionalityMap${functKey}1"
                               class="edit-contract-label">
                            <fmt:message key="edit-contract.${functKey}"/>
                        </label>
                        <form:checkbox path="functionalityMap[${functKey}]"
                                       cssErrorClass="error"
                                       value="${funct.value}"/>
                        <form:errors path="functionalityMap[${functKey}]"
                                     cssClass="alert-message error" />
                    </span>
                </c:forEach>
                </div>
            </fieldset>
            <c:forEach var="entry" items="${optionsMap}">
            <fieldset>
                <legend>
                    <fmt:message key="${entry.key}"/>
                </legend>
                <c:if test="${entry.key == 'crawl-options'}">
                    <div class="alert-message warning" >
                        <p class="fieldset-info">
                            <fmt:message key="edit-contract.crawlOptionsInfo"/>
                        </p>
                    </div>
                </c:if>
                <c:forEach var="option" items="${entry.value}" >
                    <c:set var="i18nKey"
                           scope="page"
                           value="${option.formField.i18nKey}"/>
                    <c:set var="code"
                           scope="page"
                           value="${option.option.code}"/>
                    <c:set var="contractOptionError">
                        <form:errors path="optionMap[${code}]"/>
                    </c:set>
                    <c:choose>
                        <c:when test="${not empty contractOptionError}">
                            <c:set var="contractOptionErrorClass" value="error"/>
                        </c:when>
                        <c:otherwise>
                            <c:set var="contractOptionErrorClass" value=""/>
                        </c:otherwise>
                    </c:choose>
                    <div class="clearfix ${contractOptionErrorClass}">
                        <c:choose>
                        <c:when test="${tg:instanceOf(option.formField, 'org.asqatasun.webapp.ui.form.CheckboxFormField')}">
                        <div class="set-up-value input">
                            <ul class="inputs-list">
                        <c:forEach items="${option.formField.checkboxElementList}"
                                   var="element"
                                   varStatus="pResult">
                                <li>
                                    <label class="checkbox"
                                           for="optionMap${code}${pResult.index + 1}">
                                        <form:checkbox path="optionMap[${code}]"
                                                       value="${element.value}"/>
                                        <fmt:message key="${i18nKey}"/>
                                    </label>
                                </li>
                        </c:forEach>
                            </ul>
                        </div>
                        </c:when>
                        <c:otherwise>
                        <label id="set-up-${i18nKey}"
                               for="${i18nKey}">
                            <fmt:message key="${i18nKey}"/>
                        </label>
                        <div class="set-up-value input">
                            <form:input id="${i18nKey}"
                                        path="optionMap[${code}]"
                                        cssErrorClass="xlarge error"
                                        cssClass="xlarge"/>
                            <form:errors path="optionMap[${code}]"
                                         cssClass="alert-message error" />
                            <br/>
                            <span class="help-block">
                <c:choose>
                    <c:when test="${tg:instanceOf(option.formField, 'org.asqatasun.webapp.ui.form.NumericalFormField')}">
                        <fmt:message key="${i18nKey}-rule">
                            <fmt:param>${option.formField.maxValue}</fmt:param>
                        </fmt:message>
                    </c:when>
                    <c:otherwise>
                        <fmt:message key="${i18nKey}-rule"/>
                    </c:otherwise>
                </c:choose><!-- test="instanceof NumericalFormField"-->
                </span>
                        </div>
                            </c:otherwise>
                        </c:choose>
                    </div>
                </c:forEach>
            </fieldset>
            </c:forEach>
            <div id="edit-contract-form-submit" 
                 class="actions">
                <input class="btn primary" 
                       type="submit" 
                       value="${validateButtonName}"/>
            </div>
        </form:form>
    </div><!-- id="account-settings-form" -->
</div><!-- class="span16" -->

web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/template/formula.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<p id="score-formula">
    <fmt:message key="resultPage.scoreFormula"/> 
    (1-ratio_nmi) * Passed / (Passed + Failed) + ratio_nmi *  
    <abbr title="Need More Information">
        NMI
    </abbr> / (Passed + Failed + 
    <abbr title="Need More Information">
        NMI
    </abbr>)
    <fmt:message key="resultPage.usedWith"/> 
    ${statistics.testCount} tests
    <a href="<fmt:message key="resultPage.scoreFormulaLinkURL"/>">
        <fmt:message key="resultPage.scoreFormulaLinkText"/>
    </a>
</p>

web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/template/grade.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<%--
CAUTION
if you ever change the values defining the grades, don't forget to modify also:
web-app/asqatasun-web-app/src/main/webapp/public/js/score/grade-page-list-f2xx.js
 --%>
<c:choose>
    <c:when test="${mark == 100}">
        <c:set var="grade" scope="page" value="A"/>
        <c:set var="gradeClass" scope="page" value="grade-a"/>
    </c:when>
    <c:when test="${mark > 90}">
        <c:set var="grade" scope="page" value="B"/>
        <c:set var="gradeClass" scope="page" value="grade-b"/>
    </c:when>
    <c:when test="${mark > 85}">
        <c:set var="grade" scope="page" value="C"/>
        <c:set var="gradeClass" scope="page" value="grade-c"/>
    </c:when>
    <c:when test="${mark > 75}">
        <c:set var="grade" scope="page" value="D"/>
        <c:set var="gradeClass" scope="page" value="grade-d"/>
    </c:when>
    <c:when test="${mark > 60}">
        <c:set var="grade" scope="page" value="E"/>
        <c:set var="gradeClass" scope="page" value="grade-e"/>
    </c:when>
    <c:otherwise>
        <c:set var="grade" scope="page" value="F"/>
        <c:set var="gradeClass" scope="page" value="grade-f"/>
    </c:otherwise>
</c:choose>
<div class="${spanClass} ${scoreClass}">
    <span class="grade-container ${gradeClass} ">
        <span class="grade-letter" >${grade}</span>
    </span>
</div>

web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/template/header-utils.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="sec"  %>

<c:set var="tgLogoUrl">
    <c:url value="/public/images/Logo/Logo-asqatasun-light-w193px-h48px-bgTransp.png?v${asqatasunVersion}"/>
</c:set>
<c:set var="logoutLogoUrl">
    <c:url value="/public/images/icon-logout.png?v${asqatasunVersion}"/>
</c:set>
<c:set var="adminLogoUrl">
    <c:url value="/public/images/icon-admin.png?v${asqatasunVersion}"/>
</c:set>

<c:set var="currentUserName" scope="page">
    <c:catch var="notAuthenException" >
        <sec:authentication property="principal.displayedUserName" />
    </c:catch>
</c:set>
<c:if test="${accountSettingsActive == 'true'}">
    <c:set var="accountSettingsActive" scope="page" value=""/>
</c:if>
<c:if test="${adminActive == 'true'}">
    <c:set var="adminActive" scope="page" value=""/>
</c:if>
<header class="topbar">
    <div class="fill">
        <div class="container">
            <c:choose>
                <c:when test="${empty notAuthenException}">
                <a class="brand" 
                   href="<c:url value="/"/>"
                   title="<fmt:message key="home.home"/>">
                    <img src="${tgLogoUrl}" alt="<fmt:message key="home.home"/>"/>
                </a>
                </c:when>
                <c:otherwise>
                <a class="brand" 
                   href="<c:url value="/login.html"/>" 
                   title="Login">
                    <img src="${tgLogoUrl}" alt="Login" />
                </a>
                </c:otherwise>
            </c:choose>
            <ul class="nav secondary-nav">

            <sec:authorize access="isAuthenticated()">
                <li>
                    <c:choose>
                    <c:when test="${! fn:startsWith(currentUserName, 'guest')}">
                    <div id="account-settings">
                        <a href="<c:url value="/account-settings.html"/>" 
                           title="<fmt:message key="account-settings.accountSettingsLinkTitle"><fmt:param>${currentUserName}</fmt:param></fmt:message>">
                            ${currentUserName}
                        </a>
                    </div>
                    <%@include file="lang-box.jsp" %>
                    </c:when>
                    <c:otherwise>
                        <div class="lang-switcher-offset">
                            <%@include file="lang-box.jsp" %>
                        </div>
                    </c:otherwise>
                    </c:choose>
                </li>
            </sec:authorize>
            <c:set var="isInTopBar" scope="page" value="true"/>
            <sec:authorize access="hasRole('ROLE_ADMIN')">
                <li ${adminActive}>
                    <a href="<c:url value="/admin.html"/>" 
                       title="<fmt:message key="home.admin"/>">
                        <img src="${adminLogoUrl}" 
                             alt="<fmt:message key="home.admin"/>"/>
                    </a>
                </li>    
            </sec:authorize>
            <c:if test="${empty notAuthenException}">
                <li>
                    <a href="<c:url value="/logout"/>"
                       id="logout" 
                       title="<fmt:message key="home.logout"/>">
                        <img src="${logoutLogoUrl}" 
                             alt="<fmt:message key="home.logout"/>" 
                             id="logout-icon"/>
                    </a>
                </li>
            </c:if>
            </ul><!--class="nav secondary-nav"-->
        </div><!-- class="container" -->
    </div><!-- class="fill" -->
</header><!-- class="topbar" -->

web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/template/login-form.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ page import="org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter" %>                                 

<c:set var="formClass" value="form-stacked" scope="page"/>
<c:set var="inputSize" value="input-xlarge" scope="page"/>

<div id="login-form" class="row">
    <form method="post" 
          action="<c:url value="/login"/>"
          class="${formClass}">
<c:choose>
    <c:when test="${not empty param.login_error}">
        <c:set var="usernameValue">
            <%= session.getAttribute(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_USERNAME_KEY)%>
        </c:set>
    </c:when>
    <c:when test="${not empty param.email}">
        <c:set var="usernameValue" value="${param.email}"/>  
    </c:when>
    <c:otherwise>
        <c:set var="usernameValue" value=""/>  
    </c:otherwise>
</c:choose>
<c:choose>
    <c:when test="${inline == 'true'}">
        <input type="text" 
               class="${inputSize}" 
               title="<fmt:message key="login.id"/>" 
               placeholder="<fmt:message key="login.id"/>" 
               name="username"
               id="username"
               <c:if test="${not empty usernameValue}"> value="${usernameValue}"</c:if> />
        <div class="inline-password">
            <input type="password" 
                   name="password"
                   title="<fmt:message key="login.password"/>" 
                   placeholder="<fmt:message key="login.password"/>" 
                   id="password"
                   class="${inputSize}"
                   autocomplete="off" />
            <span class="help">
                <a id="lost-password" 
                   href="<c:url value="/forgotten-password.html"/>"> 
                    <fmt:message key="login.passwordForgotten"/>
                </a>
            </span>
        </div>
        <input class="btn" 
               type="submit" 
               name="Login" 
               value="<fmt:message key="login.submit"/>"/>
    </c:when>
    <c:otherwise>
        <label for="username">
            <fmt:message key="login.id"/>
        </label>
        <input type="text" 
               class="${inputSize}" 
               name="username"
               id="username"
               <c:if test="${not empty usernameValue}"> value="${usernameValue}"</c:if> />
        <label for="password">
            <fmt:message key="login.password"/>
        </label>
        <input type="password" 
               name="password"
               id="password"
               class="${inputSize}" 
               autocomplete="off" />
        <span class="help-block">
            <a href="<c:url value="/forgotten-password.html"/>">
                <fmt:message key="login.passwordForgotten"/>
            </a>
        </span>
        <input class="btn" 
               type="submit" 
               name="Login" 
               value="<fmt:message key="login.submit"/>"/>
    </c:otherwise>
</c:choose>
    </form>
</div><!-- id="login-form" -->

web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/template/set-up.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ taglib uri="http://tagutils" prefix="tg" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>

<%-- check if at least 1 referential is enabled --%>
<c:set var="noReferentialEnabled" value="1"/>  <%-- default: no referential enabled --%>
<c:forEach var="level" items="${levelList}" >
    <c:forEach items="${level.selectElementMap}"   var="group">
        <c:if test="${group.value[0].enabled == true}">
            <c:set var="noReferentialEnabled" value="0"/> <%-- 1 referential is enabled --%>
        </c:if>
    </c:forEach>
</c:forEach>

<c:choose>
    <c:when test="${noReferentialEnabled == '1'}">
        <div class="alert-message block-message error span16">
            <h2><fmt:message key="auditSetUp.projectConfigurationError"/> </h2>
            <p><fmt:message key="auditSetUp.errorNoRefentialEnabled"/>    </p>
        </div>
    </c:when>
    <c:otherwise>
        <%@include file="set-up-form.jsp" %>
    </c:otherwise>
</c:choose>