web-app/asqatasun-web-app/src/main/java/org/asqatasun/webapp/action/Action.java
/*
 * Asqatasun - Automated webpage assessment
 * Copyright (C) 2008-2020  Asqatasun.org
 *
 * This file is part of Asqatasun.
 *
 * Asqatasun is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contact us by mail: asqatasun AT asqatasun DOT org
 */
package org.asqatasun.webapp.action;

/**
 *
 * @author jkowalczyk
 */
public class Action {

    // By default an action is disabled. 
    private boolean isActionEnabled = false;
    public boolean getActionEnabled() {
        return isActionEnabled;
    }

    public void setActionEnabled(boolean isActionEnabled) {
        this.isActionEnabled = isActionEnabled;
    }

    private String actionCode;
    public String getActionCode() {
        return actionCode;
    }

    public void setActionCode(String actionCode) {
        this.actionCode = actionCode;
    }

    private String actionI81NCode;
    public String getActionI81NCode() {
        return this.actionI81NCode;
    }

    public void setActionI81NCode(String actionI81NCode) {
        this.actionI81NCode = actionI81NCode;
    }

    private String actionAltI81NCode;
    public String getActionAltI81NCode() {
        return this.actionAltI81NCode;
    }

    public void setActionAltI81NCode(String actionAltI81NCode) {
        this.actionAltI81NCode = actionAltI81NCode;
    }

    private String actionUrl;
    public String getActionUrl() {
        return actionUrl;
    }

    public void setActionUrl(String actionUrl) {
        this.actionUrl = actionUrl;
    }

    private String enabledActionImageUrl;
    public String getEnabledActionImageUrl() {
        return enabledActionImageUrl;
    }

    public void setEnabledActionImageUrl(String enabledActionImageUrl) {
        this.enabledActionImageUrl = enabledActionImageUrl;
    }
    
    private String disabledActionImageUrl;
    public String getDisabledActionImageUrl() {
        return disabledActionImageUrl;
    }

    public void setDisabledActionImageUrl(String enabledActionImageUrl) {
        this.disabledActionImageUrl = enabledActionImageUrl;
    }

    private String cssSelector;
    public String getCssSelector() {
        return cssSelector;
    }

    public void setCssSelector(String cssSelector) {
        this.cssSelector = cssSelector;
    }

    public void doProcess() {
    //  do nothing here;
    }

}

web-app/asqatasun-web-app/src/main/java/org/asqatasun/webapp/controller/AccountSettingsController.java
/*
 * Asqatasun - Automated webpage assessment
 * Copyright (C) 2008-2020  Asqatasun.org
 *
 * This file is part of Asqatasun.
 *
 * Asqatasun is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contact us by mail: asqatasun AT asqatasun DOT org
 */
package org.asqatasun.webapp.controller;

import java.util.*;
import javax.annotation.PostConstruct;
import javax.servlet.http.HttpServletRequest;
import org.asqatasun.entity.reference.Reference;
import org.asqatasun.entity.reference.Test;
import org.asqatasun.entity.service.reference.ReferenceDataService;
import org.asqatasun.entity.service.reference.TestDataService;
import org.asqatasun.webapp.command.ChangeTestWeightCommand;
import org.asqatasun.webapp.command.CreateUserCommand;
import org.asqatasun.webapp.command.factory.ChangeTestWeightCommandFactory;
import org.asqatasun.entity.user.User;
import org.asqatasun.webapp.exception.ForbiddenPageException;
import org.asqatasun.webapp.ui.form.menu.SecondaryLevelMenuDisplayer;
import org.asqatasun.webapp.util.TgolKeyStore;
import org.asqatasun.webapp.validator.ChangeTestWeightFormValidator;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.access.annotation.Secured;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.LocaleResolver;

/** 
 *
 * @author jkowalczyk
 */
@Controller
public class AccountSettingsController extends AbstractUserAndContractsController {

    @Value("${app.webapp.ui.config.forbiddenUserListForSettings}")
    private List<String> forbiddenUserList;
    private Map<String, Reference> refMap;
    private final TestDataService testDataService;
    private final ReferenceDataService referenceDataService;
    private final LocaleResolver localeResolver;
    private final ChangeTestWeightFormValidator changeTestWeightFormValidator;
    private final SecondaryLevelMenuDisplayer secondaryLevelMenuDisplayer;
    final
    ChangeTestWeightCommandFactory changeTestWeightCommandFactory;

    /**
     * Constructor
     */
    public AccountSettingsController(TestDataService testDataService,
                                     ReferenceDataService referenceDataService,
                                     LocaleResolver localeResolver,
                                     ChangeTestWeightFormValidator changeTestWeightFormValidator,
                                     SecondaryLevelMenuDisplayer secondaryLevelMenuDisplayer,
                                     ChangeTestWeightCommandFactory changeTestWeightCommandFactory) {
        super();
        this.testDataService = testDataService;
        this.referenceDataService = referenceDataService;
        this.localeResolver = localeResolver;
        this.changeTestWeightFormValidator = changeTestWeightFormValidator;
        this.secondaryLevelMenuDisplayer = secondaryLevelMenuDisplayer;
        this.changeTestWeightCommandFactory = changeTestWeightCommandFactory;
    }

    @PostConstruct
    private void init() {
        refMap = new HashMap <>();
        for (Reference ref : referenceDataService.findAll()) {
            refMap.put(ref.getCode(), ref);
        }
    }

    /**
     * This method displays the form for an authenticated user
     * 
     * @param model
     * @return
     */
    @RequestMapping(value = TgolKeyStore.ACCOUNT_SETTINGS_URL, method = RequestMethod.GET)
    @Secured({TgolKeyStore.ROLE_USER_KEY, TgolKeyStore.ROLE_ADMIN_KEY})
    public String displayAccountSettingsPage(Model model) {
        User user = getCurrentUser();
        if (this.forbiddenUserList.contains(user.getEmail1())) {
            throw new ForbiddenPageException();
        }
        secondaryLevelMenuDisplayer.setModifiableReferentialsForUserToModel(user, model);
        return prepateDataAndReturnCreateUserView(
                model,
                user,
                TgolKeyStore.ACCOUNT_SETTINGS_VIEW_NAME);
    }

    /**
     * This methods controls the validity of the edit user form.
     * If the user tries to modidy its email, or try to desactivate its account
     * or try to set him as admin where he's not admin, return attack message.
     * 
     * @param createUserCommand
     * @param result
     * @param model
     * @return
     * @throws Exception
     */
    @RequestMapping(value = TgolKeyStore.ACCOUNT_SETTINGS_URL,method = RequestMethod.POST)
    @Secured({TgolKeyStore.ROLE_USER_KEY, TgolKeyStore.ROLE_ADMIN_KEY})
    protected String submitAccountSettingForm(
            @ModelAttribute(TgolKeyStore.CREATE_USER_COMMAND_KEY) CreateUserCommand createUserCommand,
            BindingResult result,
            Model model)
            throws Exception {
        User user = getCurrentUser();
        if (this.forbiddenUserList.contains(user.getEmail1())) {
            throw new ForbiddenPageException();
        }
        if (!createUserCommand.getEmail().equals(user.getEmail1()) ||
                (createUserCommand.getAdmin() && !isUserAdmin(user))) {
            model.addAttribute(TgolKeyStore.CREATE_USER_ATTACK_COMMAND_KEY, true);
            return prepateDataAndReturnCreateUserView(
                model,
                user,
                TgolKeyStore.ACCOUNT_SETTINGS_VIEW_NAME);
        }
        
        secondaryLevelMenuDisplayer.setModifiableReferentialsForUserToModel(user, model);
        
        return submitUpdateUserForm(
                createUserCommand, 
                result, 
                null,
                model, 
                user,
                TgolKeyStore.ACCOUNT_SETTINGS_VIEW_NAME, 
                TgolKeyStore.ACCOUNT_SETTINGS_VIEW_NAME,
                false,
                false,
                TgolKeyStore.UPDATED_USER_NAME_KEY); 
    }

    /**
     * This method displays the Change Test Weight page for the authentified user.
     * This page is displayed if and only if the current user owns at least 
     * one contract on the wished referential. 
     * 
     * @param refCode
     * @param request
     * @param model
     * @return
     */
    @RequestMapping(value = TgolKeyStore.TEST_WEIGHT_URL, method = RequestMethod.GET)
    @Secured({TgolKeyStore.ROLE_USER_KEY, TgolKeyStore.ROLE_ADMIN_KEY})
    public String displayChangeTestWeight(
            @RequestParam(TgolKeyStore.REFERENTIAL_CD_KEY) String refCode,
            HttpServletRequest request,
            Model model) {

        Reference referential = refMap.get(refCode);
        List<Test> testList = addTestListAndModifiableRefToModel(referential, model);

        model.addAttribute(TgolKeyStore.CHANGE_TEST_WEIGHT_COMMAND_KEY, 
                changeTestWeightCommandFactory.getChangeTestWeightCommand(
                    getCurrentUser(), 
                    localeResolver.resolveLocale(request),
                    testList, 
                    refCode));
        return TgolKeyStore.TEST_WEIGHT_VIEW_NAME;
    }
    
    /**
     * 
     * @param refCode
     * @param changeTestWeightCommand
     * @param result
     * @param model
     * @return
     * @throws Exception 
     */
    @RequestMapping(value = TgolKeyStore.TEST_WEIGHT_URL, method = RequestMethod.POST)
    @Secured({TgolKeyStore.ROLE_USER_KEY, TgolKeyStore.ROLE_ADMIN_KEY})
    public String submitChangeTestWeight (
            @RequestParam(TgolKeyStore.REFERENTIAL_CD_KEY) String refCode,
            @ModelAttribute(TgolKeyStore.CHANGE_TEST_WEIGHT_COMMAND_KEY) ChangeTestWeightCommand changeTestWeightCommand,
            BindingResult result,
            Model model)  {

        Reference referential = refMap.get(refCode);
        if (referential == null || 
                !secondaryLevelMenuDisplayer.isRequestedReferentialModifiable(refCode)) {
            throw new ForbiddenPageException();
        }

        // We check whether the form is valid
        changeTestWeightFormValidator.validate(changeTestWeightCommand, result);
        // If the form has some errors, we display it again with errors' details
        addTestListAndModifiableRefToModel(referential, model);

        model.addAttribute(TgolKeyStore.CHANGE_TEST_WEIGHT_COMMAND_KEY, changeTestWeightCommand);

        if (!result.hasErrors()) {
            changeTestWeightCommandFactory.updateUserTestWeight(
                getCurrentUser(),
                changeTestWeightCommand);
            model.addAttribute(TgolKeyStore.TEST_WEIGHT_SUCCESSFULLY_UPDATED_KEY, true);
        }

        return TgolKeyStore.TEST_WEIGHT_VIEW_NAME;
    }
    
    /**
     * 
     * @param ref
     * @param model
     * @return 
     */
    private List<Test> addTestListAndModifiableRefToModel(Reference ref, Model model) {
        List<Test> testList = testDataService.findAll(ref);
        sortTestListByCode(testList);
        model.addAttribute(TgolKeyStore.TEST_LIST_KEY, testList);
        
        secondaryLevelMenuDisplayer.setModifiableReferentialsForUserToModel(
                        getCurrentUser(), 
                        model);

        return testList;
    }
    
    /**

web-app/asqatasun-web-app/src/main/java/org/asqatasun/webapp/controller/HomeController.java
/*
 * Asqatasun - Automated webpage assessment
 * Copyright (C) 2008-2020  Asqatasun.org
 *
 * This file is part of Asqatasun.
 *
 * Asqatasun is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Contact us by mail: asqatasun AT asqatasun DOT org
 */
package org.asqatasun.webapp.controller;

import java.util.List;

import org.asqatasun.webapp.command.ContractSortCommand;
import org.asqatasun.webapp.command.helper.ContractSortCommandHelper;
import org.asqatasun.entity.user.User;
import org.asqatasun.webapp.exception.ForbiddenUserException;
import org.asqatasun.webapp.ui.form.builder.FormFieldBuilder;
import org.asqatasun.webapp.util.TgolKeyStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.security.access.annotation.Secured;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


/** 
 *
 * @author jkowalczyk
 */
@Controller
public class HomeController extends AbstractController {

    private final ContractSortCommandHelper contractSortCommandHelper;
    private final List<FormFieldBuilder> displayOptionFieldsBuilderList;

    @Autowired
    public HomeController(ContractSortCommandHelper contractSortCommandHelper,
                          @Qualifier(value = "displayOptionFieldsBuilderList")
                            List<FormFieldBuilder> displayOptionFieldsBuilderList) {
        super();
        this.contractSortCommandHelper = contractSortCommandHelper;
        this.displayOptionFieldsBuilderList = displayOptionFieldsBuilderList;
    }

    @RequestMapping(value=TgolKeyStore.HOME_URL, method=RequestMethod.GET)
    @Secured({TgolKeyStore.ROLE_USER_KEY, TgolKeyStore.ROLE_ADMIN_KEY})
    public String displayHomePage(Model model) {
        User user = getCurrentUser();
        model.addAttribute(
                TgolKeyStore.CONTRACT_LIST_KEY, 
                contractSortCommandHelper.prepareContractInfo(
                    user, 
                    null,
                    displayOptionFieldsBuilderList,
                    model));
        return TgolKeyStore.HOME_VIEW_NAME;
    }

    @RequestMapping(value=TgolKeyStore.HOME_URL, method = RequestMethod.POST)
    @Secured({TgolKeyStore.ROLE_USER_KEY, TgolKeyStore.ROLE_ADMIN_KEY})
    protected String submitForm(
            @ModelAttribute(TgolKeyStore.CONTRACT_SORT_COMMAND_KEY) ContractSortCommand contractDisplayCommand,
            Model model) {
        User user = getCurrentUser();
        if (!user.getId().equals(contractDisplayCommand.getUserId())) {
            throw new ForbiddenUserException();
        }
        // The page is displayed with sort option. Form needs to be set up
        model.addAttribute(
                TgolKeyStore.CONTRACT_LIST_KEY, 
                contractSortCommandHelper.prepareContractInfo(
                    user, 
                    contractDisplayCommand,
                    displayOptionFieldsBuilderList,
                    model));
        return TgolKeyStore.HOME_VIEW_NAME;
    }
    
}

web-app/asqatasun-web-app/src/main/webapp/WEB-INF/view/result-page-by-criterion.jsp
<%@ taglib uri="http://htmlcompressor.googlecode.com/taglib/compressor" prefix="compress" %>
<compress:html>
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://tagutils" prefix="tg" %>
<!DOCTYPE html>
<%@include file="/WEB-INF/view/template/template_variables.jspf" %>

<!-- external js -->
<c:set var="jqueryUrl">
    <c:url value="/public/external_js/jquery-1.11.1.min.js?v${asqatasunVersion}"/>
</c:set>        
<c:set var="jqueryUIUrl">
    <c:url value="/public/external_js/jquery-ui-1.10.1.custom.min.js?v${asqatasunVersion}"/>
</c:set>
<c:set var="d3JsUrl" scope="request">
    <c:url value="/public/external_js/d3.v3.min.js?v${asqatasunVersion}"/>
</c:set>
<c:set var="r2d3JsUrl" scope="request">
    <c:url value="/public/external_js/r2d3.v2.min.js?v${asqatasunVersion}"/>
</c:set> 

<!-- internal js -->
<c:set var="resultPageChartsJsIEUrl" scope="request">
    <c:url value="/public/js/ie/result-page/result-page-charts-ie-min.js?v${asqatasunVersion}"/>
</c:set>
<c:set var="resultPageChartsJsUrl" scope="request">
    <c:url value="/public/js/result-page/result-page-charts-min.js?v${asqatasunVersion}"/>
</c:set>
<c:set var="scoreJsUrl" scope="request">
    <c:url value="/public/js/score/score-min.js?v${asqatasunVersion}"/>
</c:set>
<c:set var="themeDetailsJsUrl" scope="page">
    <c:url value="/public/js/expand-collapse/theme-details-min.js?v${asqatasunVersion}"/>
</c:set>
<c:set var="auditParametersDetailsJsUrl" scope="page">
    <c:url value="/public/js/expand-collapse/audit-parameters-details-min.js?v${asqatasunVersion}"/>
</c:set>
<c:set var="progressBarJsUrl" scope="page">
    <c:url value="/public/js/progress-bar/progress-bar-min.js?v${asqatasunVersion}"/>
</c:set>
<c:set var="displaySnapshotJsUrl" scope="page">
    <c:url value="/public/js/snapshot/snapshot-min.js?v${asqatasunVersion}"/>
</c:set>

<!-- external img -->
<c:set var="expandedImg" scope="request">
    <c:url value="/public/images/expanded.png?v${asqatasunVersion}"/>
</c:set> 
<c:set var="collapsedImg" scope="request">
    <c:url value="/public/images/collapsed.png?v${asqatasunVersion}"/>
</c:set> 
<c:set var="sourceCodeImg" scope="request">
    <c:url value="/public/images/html-source-icon.png?v${asqatasunVersion}"/>
</c:set>
<c:set var="processingImgUrl" scope="request">
    <c:url value="/public/images/processing.gif?v${asqatasunVersion}"/>
</c:set>

<c:if test="${statistics.auditScope == 'DOMAIN' || statistics.auditScope == 'PAGE'}">
    <c:set var="addRelaunchAction" scope="page" value="true"/>
</c:if>
<html lang="${tg:lang(pageContext)}">
    <c:set var="pageTitle" scope="page">
        <fmt:message key="resultPageByCriterion.pageTitle">
            <fmt:param>
                ${statistics.url}
            </fmt:param>
        </fmt:message>
    </c:set>
    <c:if test="${addRelaunchAction}">
        <c:set var="addJqueryUI" scope="request" value="true"/>
    </c:if>        
    <%@include file="template/head.jsp" %>
    <body id="tgm-result-page">
        <%@include file="template/header-utils.jsp" %>
        <main class="container">
            <c:set var="pageName" scope="page">
                <fmt:message key="resultPage.h1"/>
            </c:set>
            <ul class="breadcrumb">
                <li><a href="<c:url value="/home.html"/>"><fmt:message key="home.h1"/></a> <span class="divider"></span></li>
                <li><a href="<c:url value="/home/contract.html?cr=${cr}"/>">${contractName}</a> <span class="divider"></span></li>
                <c:if test="${authorizedScopeForPageList == 'true'}">
                    <c:set var="auditSynthesisName" scope="page">
                        <fmt:message key="synthesisSite.h1">
                            <fmt:param>
                                ${audit}
                            </fmt:param>
                        </fmt:message>
                    </c:set>
                    <li><a href="<c:url value="/home/contract/audit-synthesis.html?audit=${audit}"/>">${auditSynthesisName}</a> <span class="divider"></span></li>
                    <li><a href="<c:url value="/home/contract/page-list.html?audit=${audit}"/>"><fmt:message key="pageList.h1"/></a> <span class="divider"></span></li>
                    <c:choose>
                        <c:when test="${statistics.auditScope == 'DOMAIN'}">
                            <c:set var="pageList2xxUrl" value="/home/contract/page-list.html?audit=${audit}&amp;status=f2xx"/>
                        </c:when>
                        <c:when test="${statistics.auditScope == 'SCENARIO'}">
                            <c:set var="pageList2xxUrl" value="/home/contract/page-list.html?audit=${audit}&amp;status=f2xx&amp;sortCriterion=rank&amp;sortDirection=1"/>
                        </c:when>
                    </c:choose>
                    <li><a href="<c:url value="${pageList2xxUrl}"/>"><fmt:message key="pageList.f2xx.h1"/></a> <span class="divider"></span></li>
                </c:if>
                <li class="active">${pageName}</li>
            </ul>
            <div id="result-page-title" class="row">
                <div class="span8">
                    <h1>
                        ${contractName}
                    </h1>
                </div>
                <div class="span6 offset2">
                    <c:if test="${addRelaunchAction}">
                    <div id="relaunch-action">
                        <c:set var="postUrl">
                            <c:url value="/home/contract/audit-page-set-up.html?cr=${auditSetUpCommand.contractId}"/>
                        </c:set>
                        <form:form modelAttribute="auditSetUpCommand" action="${postUrl}" method="post" enctype="multipart/form-data">
                            <form:hidden path="urlList[0]"/>
                            <form:hidden path="scope"/>
                            <form:hidden path="auditParameter"/>
                            <form:hidden path="relaunch"/>
                            <form:hidden path="contractId"/>
                            <form:hidden path="level"/>
                            <div id="relaunch-audit-form-submit">
                                <input id="launch-audit-submit" type="submit" class="relaunch-button result-page-action" value="<fmt:message key="resultPage.relaunchAudit"/>"/>
                            </div>
                            <%@include file="template/process-pop-up.jsp" %>
                        </form:form>
                    </div>
                    </c:if>
                    <div id="export-actions">
                        <fmt:message key="result.export"/> : 
                        <c:if test="${resultActionList != null && not empty resultActionList}">
                            <c:forEach var="action" items="${resultActionList}" varStatus="pAction">
                                <c:choose>
                                    <c:when test="${action.actionEnabled == 'false'}">
                            <span class="export-action">
                                <c:if test="${pAction.index != 0}">
                                    /
                                </c:if>
                                <a href="<c:url value="${action.actionUrl}&amp;wr=${param.wr}"/>" class="disabled" title="<fmt:message key="${action.actionAltI81NCode}"/> (<fmt:message key="contract.disabled"/>)">
                                    <fmt:message key="${action.actionI81NCode}"/>
                                </a>
                            </span>
                                    </c:when>
                                    <c:otherwise>
                            <span class="export-action">
                                <c:if test="${pAction.index != 0}">
                                    /
                                </c:if>
                                <!-- the url actions already have a parameter (export type for example-->
                                <a href="<c:url value="${action.actionUrl}&amp;wr=${param.wr}"/>" title="<fmt:message key="${action.actionAltI81NCode}"/>">
                                    <fmt:message key="${action.actionI81NCode}"/>
                                </a>
                            </span>
                                    </c:otherwise>
                                </c:choose>
                            </c:forEach>
                        </c:if>    
                    </div>  
                </div>  
            </div><!-- class="row" -->
            <c:set var="showLegend" scope="request" value="true"/>
            <c:set var="showAxisLabel" scope="request" value="true"/>
            <c:set var="hasBarChartLink" scope="request" value="true"/>
            <c:set var="hasGraphics" scope="request" value="true"/>
            <c:set var="hasSynthesisTitle" scope="request" value="false"/>
            <c:set var="hasPageCounter" scope="request" value="false"/>
            <c:set var="hasPagesListLink" scope="request" value="false"/>
            <c:set var="hasResultDispatchTitle" scope="request" value="false"/>
            <c:set var="themeRepartitionWidth" scope="request" value="690"/>
            <c:set var="hasPieChartInGraphicalResult" scope="request" value="true"/>
            <c:set var="addLinkToSourceCode" scope="request" value="true"/>
            <c:import url="template/synthesis.jsp" />
            <c:import url="template/sort-result-console.jsp" />
            <c:set var="displayAlgorithm" scope="request" value="true"/>
            <c:set var="scope" scope="request" value="page"/>
            <c:import url="template/detailed-result-by-criterion.jsp" />
        </main><!-- class="container"-->
        <%@include file="template/footer.jsp" %>
        <script type="text/javascript" src="${jqueryUrl}"></script>
        <script type="text/javascript" src="${themeDetailsJsUrl}"></script>
        <script type="text/javascript" src="${auditParametersDetailsJsUrl}"></script>
        <c:if test="${addRelaunchAction}">
            <script type="text/javascript" src="${jqueryUIUrl}"></script>
            <script type="text/javascript" src="${progressBarJsUrl}"></script>
        </c:if>
        <script type="text/javascript" src="${d3JsUrl}"></script>
        <script type="text/javascript" src="${resultPageChartsJsUrl}"></script>
        <c:if test="${configProperties['displayGradeAsResult'] == 'false'}">
            <script type="text/javascript" src="${scoreJsUrl}"></script>
        </c:if>
        <!--[if lte IE 8]>
        <script type="text/javascript" src="${r2d3JsUrl}"></script>
        <script type="text/javascript" src="${resultPageChartsJsIEUrl}"></script>
        <![endif]-->
        <script type="text/javascript" src="${displaySnapshotJsUrl}"></script>
    </body>
</html>
</compress:html>